server:
  port: 8001

spring:
  application:
    name: cloud_payment_service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/cloud_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   #nacos地址

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.luop.entity    #所有entity别名类所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #打印日志到控制台

#监控
management:
  endpoints:
    web:
      exposure:
        include: '*'