server:
  port: 7001

spring:
  application:
    name: cloud_order_service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   #nacos地址


#监控
management:
  endpoints:
    web:
      exposure:
        include: '*'